-include Makefile.config

WARNINGS ?= -Wall -Wextra -Wpedantic
CFLAGS   := -std='gnu11'   -fPIC $(WARNINGS) $(DEFS) $(OMP_FLAGS) $(CFLAGS)
CXXFLAGS := -std='gnu++11' -fPIC $(WARNINGS) $(DEFS) $(OMP_FLAGS) $(CXXFLAGS)
LDFLAGS  := $(OMP_FLAGS) $(LDFLAGS)
