TESTS = \
        jac1d_1000_50_10 \
        jac1d_100 \
        jac2d_-s_1000 \
        jac2d_-s_-n_1000 \
        jac3d_-r_-s_100 \
        jac3d_-s_100 \
        jac3d_-s_-n_100 \
        markov2_40_4 \
        markov2_-f_500_5 \
        markov_40_4 \
        propagation2d_10_10 \
        spmv2_10_3000 \
        spmv2_-r_10_3000 \
        spmv2_-s_2_10_3000 \
        spmv2_-s_2_-i_10_3000 \
        spmv_4000 \
        vsum2 \
        vsum \
	kvstest locationtest

all: $(TESTS)

jac1d_1000_50_10:
	$(SDIR)./jac1d_1000_50_10.sh

jac1d_100:
	$(SDIR)./jac1d_100.sh

jac2d_-s_1000:
	$(SDIR)./jac2d_-s_1000.sh

jac2d_-s_-n_1000:
	$(SDIR)./jac2d_-s_-n_1000.sh

jac3d_-r_-s_100:
	$(SDIR)./jac3d_-r_-s_100.sh

jac3d_-s_100:
	$(SDIR)./jac3d_-s_100.sh

jac3d_-s_-n_100:
	$(SDIR)./jac3d_-s_-n_100.sh

markov2_-f_500_5:
	$(SDIR)./markov2_-f_500_5.sh

markov2_40_4:
	$(SDIR)./markov2_40_4.sh

markov_40_4:
	$(SDIR)./markov_40_4.sh

propagation2d_10_10:
	$(SDIR)./propagation2d_10_10.sh

spmv2_10_3000:
	$(SDIR)./spmv2_10_3000.sh

spmv2_-r_10_3000:
	$(SDIR)./spmv2_-r_10_3000.sh

spmv2_-s_2_10_3000:
	$(SDIR)./spmv2_-s_2_10_3000.sh

spmv2_-s_2_-i_10_3000:
	$(SDIR)./spmv2_-s_2_-i_10_3000.sh

spmv_4000:
	$(SDIR)./spmv_4000.sh

vsum2:
	$(SDIR)./vsum2.sh

vsum:
	$(SDIR)./vsum.sh

kvstest:
	$(SDIR)./kvstest.sh

locationtest:
	$(SDIR)unit/locationtest.sh
