/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: laik_ext.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/laik_ext.pb-c.h"
void   laik_ext_msg__init
                     (LaikExtMsg         *message)
{
  static LaikExtMsg init_value = LAIK_EXT_MSG__INIT;
  *message = init_value;
}
size_t laik_ext_msg__get_packed_size
                     (const LaikExtMsg *message)
{
  assert(message->base.descriptor == &laik_ext_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t laik_ext_msg__pack
                     (const LaikExtMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &laik_ext_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t laik_ext_msg__pack_to_buffer
                     (const LaikExtMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &laik_ext_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LaikExtMsg *
       laik_ext_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LaikExtMsg *)
     protobuf_c_message_unpack (&laik_ext_msg__descriptor,
                                allocator, len, data);
}
void   laik_ext_msg__free_unpacked
                     (LaikExtMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &laik_ext_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor laik_ext_msg__field_descriptors[2] =
{
  {
    "failing_nodes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(LaikExtMsg, n_failing_nodes),
    offsetof(LaikExtMsg, failing_nodes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spare_nodes",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(LaikExtMsg, n_spare_nodes),
    offsetof(LaikExtMsg, spare_nodes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned laik_ext_msg__field_indices_by_name[] = {
  0,   /* field[0] = failing_nodes */
  1,   /* field[1] = spare_nodes */
};
static const ProtobufCIntRange laik_ext_msg__number_ranges[2 + 1] =
{
  { 2, 0 },
  { 4, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor laik_ext_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "laik_ext_msg",
  "LaikExtMsg",
  "LaikExtMsg",
  "",
  sizeof(LaikExtMsg),
  2,
  laik_ext_msg__field_descriptors,
  laik_ext_msg__field_indices_by_name,
  2,  laik_ext_msg__number_ranges,
  (ProtobufCMessageInit) laik_ext_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
